# Generated by Django 4.0.8 on 2022-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitapl_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_created=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_location', models.CharField(max_length=100)),
                ('hospital_start_time', models.TimeField()),
                ('hostptal_end_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': ' Hospital service',
                'ordering': ['-post_date'],
            },
        ),
    ]
