# Generated by Django 4.0.8 on 2022-10-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitapl_service',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
