# Generated by Django 4.0.8 on 2022-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_hospital_service_delete_hospitapl_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_service',
            name='hospital_phone',
            field=models.CharField(default='0788101020', max_length=250),
        ),
    ]
